<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# Peer Review Assignment - Data Engineer - ETL

Estimated time needed: **20** minutes

## Objectives

In this final part you will:

*   Run the ETL process
*   Extract bank and market cap data from the JSON file `bank_market_cap.json`
*   Transform the market cap currency using the exchange rate data
*   Load the transformed data into a seperate CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!pip install glob
#!pip install pandas
#!pip install requests
#!pip install datetime

## Imports

Import any additional libraries you may need here.

In [1]:
import glob
import pandas as pd
from datetime import datetime

As the exchange rate fluctuates, we will download the same dataset to make marking simpler. This will be in the same format as the dataset you used in the last section

In [2]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

--2021-12-02 13:48:40--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2815 (2.7K) [application/json]
Saving to: ‘bank_market_cap_1.json’

bank_market_cap_1.j 100%[===================>]   2.75K  --.-KB/s    in 0s

2021-12-02 13:48:41 (105 MB/s) - ‘bank_market_cap_1.json’ saved [2815/2815]

--2021-12-02 13:48:42--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1429 (1.4K) [application/json]
Saving to: ‘bank_market_cap_2.json’

bank_market_cap_2.j 100%[===================>]   1.40K  --.-KB/s    in 0s

2021-12-02 13:48:42 (59.8 MB/s) - ‘bank_market_cap_2.json’ saved [1429/1429]

--2021-12-02 13:48:43--  https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv
Resolving cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)... 169.63.118.104
Connecting to cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud (cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud)|169.63.118.104|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 590 [text/csv]
Saving to: ‘exchange_rates.csv’

exchange_rates.csv  100%[===================>]     590  --.-KB/s    in 0s

2021-12-02 13:48:44 (22.1 MB/s) - ‘exchange_rates.csv’ saved [590/590]

## Extract

### JSON Extract Function

This function will extract JSON files.

In [3]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

In [5]:
!ls

bank_market_cap_1.json	bank_market_cap_2.json	exchange_rates.csv

## Extract Function

Define the extract function that finds JSON file `bank_market_cap_1.json` and calls the function created above to extract data from them. Store the data in a `pandas` dataframe. Use the following list for the columns.

In [24]:
def extract(file="bank_market_cap_1.json"):
    extracted_data = pd.DataFrame(columns = ['Name', 'Market Cap (US$ Billion)'])
    extracted_data = extracted_data.append(extract_from_json(file), ignore_index = True)
    return extracted_data

<b>Question 1</b> Load the file <code>exchange_rates.csv</code> as a dataframe and find the exchange rate for British pounds with the symbol <code>GBP</code>, store it in the variable  <code>exchange_rate</code>, you will be asked for the number. Hint: set the parameter  <code>index_col</code> to 0.

In [9]:
# Write your code here
df_2 = pd.read_csv("exchange_rates.csv", index_col = 0)
df_2.head()

        Rates
AUD  1.297088
BGN  1.608653
BRL  5.409196
CAD  1.271426
CHF  0.886083

In [15]:
exchange_rate = df_2.loc["GBP"].values[0]
print(f"exchange_rate = {exchange_rate}")

exchange_rate = 0.7323984208000001

## Transform

Using <code>exchange_rate</code> and the `exchange_rates.csv` file find the exchange rate of USD to GBP. Write a transform function that

1.  Changes the `Market Cap (US$ Billion)` column from USD to GBP
2.  Rounds the Market Cap (US$ Billion)\` column to 3 decimal places
3.  Rename `Market Cap (US$ Billion)` to `Market Cap (GBP$ Billion)`

In [20]:
def transform(df):
    # Write your code here
    gbp = df["Market Cap (US$ Billion)"] * exchange_rate
    df["Market Cap (GBP$ Billion)"] = gbp
    return df.drop(["Market Cap (US$ Billion)"], axis = 1)

## Load

Create a function that takes a dataframe and load it to a csv named `bank_market_cap_gbp.csv`. Make sure to set `index` to `False`.

In [36]:
def load(df):
    # Write your code here
    df.to_csv("bank_market_cap_gbp.csv", index = False)

## Logging Function

Write the logging function <code>log</code> to log your data:

In [35]:
def log(message):
    # Write your code here
    timestamp_format = '%Y-%h-%d-%H:%M:%S' # Year-Monthname-Day-Hour-Minute-Second
    now = datetime.now() # get current timestamp
    timestamp = now.strftime(timestamp_format)
    with open("logfile.txt", "a") as f:
        f.write(timestamp + ',' + message + '\n')

## Running the ETL Process

Log the process accordingly using the following <code>"ETL Job Started"</code> and <code>"Extract phase Started"</code>

In [23]:
# Write your code here
log("ETL Job Started")
log("Extract phase Started")

### Extract

<code>Question 2</code> Use the function <code>extract</code>, and print the first 5 rows, take a screen shot:

In [25]:
# Call the function here
df = extract()
# Print the rows here
df.head()

                                      Name  Market Cap (US$ Billion)
0                           JPMorgan Chase                   390.934
1  Industrial and Commercial Bank of China                   345.214
2                          Bank of America                   325.331
3                              Wells Fargo                   308.013
4                  China Construction Bank                   257.399

Log the data as <code>"Extract phase Ended"</code>

In [26]:
# Write your code here
log("Extract phase Ended")

### Transform

Log the following  <code>"Transform phase Started"</code>

In [27]:
# Write your code here
log("Transform phase Started")

<code>Question 3</code> Use the function <code>transform</code> and print the first 5 rows of the output, take a screen shot:

In [28]:
# Call the function here
df = transform(df = df)
# Print the first 5 rows here
df.head()

                                      Name  Market Cap (GBP$ Billion)
0                           JPMorgan Chase                 286.319444
1  Industrial and Commercial Bank of China                 252.834188
2                          Bank of America                 238.271911
3                              Wells Fargo                 225.588235
4                  China Construction Bank                 188.518621

Log your data <code>"Transform phase Ended"</code>

In [29]:
# Write your code here
log("Transform phase Ended")

### Load

Log the following `"Load phase Started"`.

In [30]:
# Write your code here
log("Load phase Started")

Call the load function

In [33]:
# Write your code here
load(df = df)

Log the following `"Load phase Ended"`.

In [34]:
# Write your code here
log("Load phase Ended")

## Authors

Ramesh Sannareddy, Joseph Santrcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).